#!/bin/bash

name=$(jq -r '.name' data.json)
type=$(jq -r '.types[0].type.name' data.json)
height=$(jq -r '.height' data.json)
weight=$(jq -r '.weight' data.json)

formatted_height=$(echo "$height" | awk '{print $1 / 10}')
formatted_weight=$(echo "$weight" | awk '{print $1 / 10}')

output="$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."

echo "$output"
