#!/bin/bash

name=$(jq -r '.name' data.json | sed 's/^/Name: /')
type=$(jq -r '.types[0].type.name' data.json | sed 's/^/Type: /')
height=$(jq -r '.height' data.json | sed 's/^/Height: /')
weight=$(jq -r '.weight' data.json | sed 's/^/Weight: /')

formatted_name=$(echo "$name" | sed 's/Name: //')
formatted_type=$(echo "$type" | sed 's/Type: //')
formatted_height=$(echo "$height" | sed 's/Height: //')
formatted_weight=$(echo "$weight" | sed 's/Weight: //')

converted_height=$(echo "$formatted_height" | awk '{print $1 / 10}')
converted_weight=$(echo "$formatted_weight" | awk '{print $1 / 10}')

echo "$formatted_name is of type $formatted_type, weighs ${converted_weight}kg, and is ${converted_height}m tall."
